graph:
  _target_: examples.ppo_trainer.config.reflection.create_reflection_agent
  sandboxfusion_api: http://sandbox-fusion:8080
chat_template_kwargs:
  tools:
    - _target_: langchain_core.utils.function_calling.convert_to_openai_function
      function:
        _target_: examples.ppo_trainer.config.reflection.create_sandboxfusion_tool
        sandboxfusion_api: dummy
