# sppo_trainer.yaml will override ppo_trainer.yaml

hydra:
  searchpath:
    - file://verl/trainer/config

defaults:
  - ppo_trainer
  - _self_

actor_rollout_ref:
  actor:
    sppo_eta: 1.0

algorithm:
  adv_estimator: null
  sppo_eta: 1.0